# Generated by Django 6.0.1 on 2026-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
    ]
