# Generated by Django 6.0.1 on 2026-02-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
