# Generated by Django 6.0.1 on 2026-03-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
